### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by haeli05** [athletics/particles#2]

**Comment by jp1971** [comment]
Hi @haeli05. Could you please provide a bit more information, and we'll see what we can do?

**Comment by brittonwalker** [comment]
@haeli05 To pass the particle images to the JS you will need to run a local server. There aare many ways to do this, but I generally run this command in the terminal from the root folder of the project:

`php -S localhost:8000`

You'll then want to point your browser to:
http://localhost:8000/

I've tested this and it works.
